### ISSUE TITLE
Create Dockerfile for easy project deployment

### ISSUE THREAD

**Issue by felipemacedo1** [BliShem/CryptoTool#9]
### Description:
Add a Dockerfile to allow the CryptoTool project to be run in containers easily and efficiently.

### Acceptance Criteria:
- [ ] The Dockerfile should include all necessary dependencies to run the project.
- [ ] Allow the CLI to be executed directly within the container.
- [ ] Include usage instructions in the README.

### Labels:
- `Enhancement`
- `Medium Priority`

### Milestone:
- vBeta
